/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class exo3 */

#ifndef _Included_exo3
#define _Included_exo3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     exo3
 * Method:    getPid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_exo3_getPid
  (JNIEnv *, jclass);

/*
 * Class:     exo3
 * Method:    createFork
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_exo3_createFork
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
