/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class exo4 */

#ifndef _Included_exo4
#define _Included_exo4
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     exo4
 * Method:    getPid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_exo4_getPid
  (JNIEnv *, jclass);

/*
 * Class:     exo4
 * Method:    pfork
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_exo4_pfork
  (JNIEnv *, jclass);

/*
 * Class:     exo4
 * Method:    pexit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_exo4_pexit
  (JNIEnv *, jclass, jint);

/*
 * Class:     exo4
 * Method:    psleep
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_exo4_psleep
  (JNIEnv *, jclass, jint);

/*
 * Class:     exo4
 * Method:    pwait
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_exo4_pwait
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
